/*
 * SesSuite.java
 * JUnit based test
 *
 * Created on October 30, 2007, 10:05 PM
 */

package ses;

import junit.framework.*;

/**
 *
 * @author Seth Sims
 */
public class SesSuite extends TestCase {

    public SesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }


    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("SesSuite");
        suite.addTest(ses.math.MathSuite.suite());
        suite.addTest(ses.util.UtilSuite.suite());
        suite.addTest(ses.Generators.GeneratorsSuite.suite());
        return suite;
    }

}
