/*
 * MathSuite.java
 * JUnit based test
 *
 * Created on October 30, 2007, 10:05 PM
 */

package ses.math;

import junit.framework.*;

/**
 *
 * @author Seth Sims
 */
public class MathSuite extends TestCase {

    public MathSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("MathSuite");
        suite.addTest(ses.math.Geometry.GeometrySuite.suite());
        suite.addTest(ses.math.MathBaseTest.suite());
        suite.addTest(ses.math.linearAlgebra.LinearAlgebraSuite.suite());
        return suite;
    }

}
