/*
 * UtilSuite.java
 * JUnit based test
 *
 * Created on November 22, 2007, 11:30 AM
 */

package ses.util;

import junit.framework.*;

/**
 *
 * @author Seth Sims
 */
public class UtilSuite extends TestCase {
    
    public UtilSuite(String testName) {
        super(testName);
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("UtilSuite");
        suite.addTest(ses.util.HashCodeTest.suite());
        return suite;
    }
    
}
