/*
 * GeometrySuite.java
 * JUnit based test
 *
 * Created on October 30, 2007, 10:05 PM
 */

package ses.math.Geometry;

import junit.framework.*;

/**
 *
 * @author Seth Sims
 */
public class GeometrySuite extends TestCase {
    
    public GeometrySuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("GeometrySuite");
        suite.addTest(ses.math.Geometry.Line2dTest.suite());
        suite.addTest(ses.math.Geometry.ParametricLine2dTest.suite());
        suite.addTest(ses.math.Geometry.Point2dTest.suite());
        return suite;
    }
    
}
