/*
 * LinearAlgebraSuite.java
 * JUnit based test
 *
 * Created on October 30, 2007, 10:05 PM
 */

package ses.math.linearAlgebra;

import junit.framework.*;

/**
 *
 * @author Seth Sims
 */
public class LinearAlgebraSuite extends TestCase {
    
    public LinearAlgebraSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("LinearAlgebraSuite");
        suite.addTest(ses.math.linearAlgebra.Vector2dTest.suite());
        suite.addTest(ses.math.linearAlgebra.SquareMatrix2Test.suite());
        return suite;
    }
    
}
